const RANDOM_QUOTES = [
  "Break a thing, and you have fragments. Break those fragments, and you have dust. Break the dust, and then break what remains. Here is fire.",
  "I knew a man who captured moths in a bell-jar. On nights like this, he would release them one by one to die in the candle.",
  "Once again, I dream of a glow beneath the filthy skin of the world. The light through the black wood. The pale door.",
  "The Wheel still turns in the house of the Moon.",
  "Friends, Foes - and those still to be determined.",
  "'If I were only here to cause mischief, dear, and I told you as much, wouldn't that also mean I was here to bring you a message?' - Aunt Mopsy, Collector of proverbs, connoisseur of wines, herald of the Hour called Mare-in-the-Tree.",
  "Not every Door is a Wound, but every Wound is a Door.",
  "This message will find its destination... once properly sanctioned by the powers of the post-box.",
  "CAPUT GERAT LUPINUM. The Sun was divided, and this is its wound.",
  "In the forests of the first continent, our ancestors cursed themselves with their own god.",
  "The Centipede told me her jokes and in exchange I will let her carve me eyes of gold, until the ommatidia occur.",
  "Cunning is the root of victory. Experience is the root of cunning. There can be no experience without suffering, and a scar is suffering given form.",
  "In each rebirth there is greater strength. What has been broken can be reforged. What has never been broken must be reforged.",
  "Thirza's advice on the shapeless Wood-things known as Raw Prophets is typically practical: (1) discourage them with buckets of water as close as possible to freezing, and with the smoke of dried lemongrass (2) under no circumstances kiss them or receive kisses from them. (3) an effective formula is provided for laundering clothes stained with Prophet-slime.",
  "'Hee hee hee hee hee hee hee hee hee. Hee.' -Valentine Dewulf",
  "The Woods grow around the walls of The Mansus. As any student of the invisible arts would know, The Mansus has no walls.",
  "THREE NATURES HATH THE WOLF DIVIDED! HE UNMAKETH! HE UNMAKETH!! AT LAST HE UNMAKETH!!!",
  "'Mercy', said The Watchman, 'is only found in shadow.'",
  "Invisible arts are as profitable as macrame, as ethical as tobacco smuggling and in general as beneficial as roulette.",
  "Porter was a Barber. Until the court case.",
  "Every choice has its shadow.",
  "If there are laws which apply only in dream - then it must also be that there are crimes which can only be committed there.",
  "You've had them too; those moments when we seem to look out at the world through another's eyes. What if those moments were real?",
  "Pine scent and bougainvillea, white walls and ocean light, sirocco winds and the smoulder of revolution.",
  "There are more windows in my soul. But sunlight is not the only thing that passes through a window.",
  "It is the emptiness that makes the bowl useful. -Lao Tzu",
  "If the cloud were a canvas, who spread it?",
  "Speech is a Wound; Silence is Silver.",
  "Everything ultimately comes down to a choice between Eternity and History. There's only one place you're safe from both, and it's a not a place anyone would want to be.",
  "'       please'",
  "Birth and death are only directions. Between the two we find a crossroads.",
  "The sea has always been the widest road.",
  "'Every regret is a lesson. We cannot change what is past, but neither should we wish to. Regret is Illumination.' - Tomorrow's Light",
  "Without distinction and perception, pleasure cannot be distinguished from pain.",
  "'I will be forgotten,' he declares, 'and this work my only trace.'",
  "Books are the memory that does not die.",
  "Secrets are soft; night is softer still; the sea speaks. It is not always wise to listen.",
  "Sunset. Time to move.",
  "Knowledge is the terror of oppressors.",
  "Their punishment is this: now that they know I live, they cannot rest until they devour me.",
  "You can stay,' the Prior tells me. 'But I won't take your money. It's the Devil who is coming for you. There's no sanctuary for you here, or anywhere on the face of the earth.",
  "The book contains diagrams. The diagrams are not pleasant to look upon.",
  "Clovette wields her joy like a hammer.",
  "Lalla Chaima has left a message at the hotel where I used to stay. It's one word: 'Noon.' It doesn't tell me where I need to be at noon, but Chaima has always been good at finding people when she needs to.",
  "Unwise words are dangerous. Mourn them, remember them, speak them not.",
  "When I wake, my face is wracked with tears of joy. That light! Cleaner than anything I see in waking life.",
  "Some words can only be spelled correctly with the proper ink.",
  "There is a stain half way down the side where, some time in the mid 1830s, Solomon Husher spilt his tea when he heard that Julian Coseley had apologised.",
  "A power of the Wood enjoys the separation of the lock from the scalp. For attention, burn it. For opportunity, bury it.",
  "(...)",
  "Slee speaks earnestly of his theories to all who will listen: the stars as tiny wounds, and the Sun as a haemorrhage of glory. His poetry is more eccentric than ever.",
  "Cover your eyes, if you like. It will serve no purpose.",
  "To open certain Ways, one must first open oneself.",
  "ALIIS SI LICET, TIBI NON LICET ( IT IS PERMITTED TO US; IT IS NOT PERMITTED TO YOU )",
  "Light LEAKS through the CRACKS. My mind is BRIGHTER than it EVER was. THE HIGHER I RISE THE MORE I SEE.",
  "The Glory is a question, and the Moth always answers Yes",
  "Copper, coal, fire, cinnamon, sunlight, obsidian. Add salt to taste. Serve. That's Ithastry.",
  "Sometimes we eat the wolf, and sometimes the wolf eats us.",
  "To reach the Stag Door, I believe that all you really need is to want something enough. But I've never wanted anything that much, except of course Baldomera, and I'm very much afraid that the knot in the story is this: what Baldomera wants is the Stag Door.",
  "I'm going to send my Foe a weapon of power. Because it'll really annoy them.",
  "Even sand may some day be the eye of rock.",
  "Sixty years ago the Swan King staged a grandiose première of his favourite composer's new opera. It didn't go well.",
  "Break a window. What have you made? A new way? A new light? A new weapon? - Natalia Brulleau",
  "What in the Wolf-Divided's most splintered Name hath here been wrought?",
  "The precise colour of the hours when one cannot sleep.",
  "Into the Wood in dark of night\n\nI made my way with fire's sight\n\nTo a silent forest of lights\n\nWhere I found a gold apple bright",
  "I dreamt of the rain, whispering in the eaves, tapping on windows like an old friend, hissing prankishly in the chimney. It is difficult to be unhappy in the right kind of rain.",
];
module.exports = { RANDOM_QUOTES };
