const { ASPECT_NAMES } = require("./core");

const CONCEPT_TYPES = {
  APOLLONIAN: "Apollonian",
  DYONISIAN: "Dyonisian",
  UNCERTAIN: "Uncertain",
  TRANSCENDANT: "Transcendant",
};

const ASPECT_CONCEPTS = {
  [ASPECT_NAMES.EDGE]: CONCEPT_TYPES.APOLLONIAN,
  [ASPECT_NAMES.FORGE]: CONCEPT_TYPES.APOLLONIAN,
  [ASPECT_NAMES.GRAIL]: CONCEPT_TYPES.DYONISIAN,
  [ASPECT_NAMES.HEART]: CONCEPT_TYPES.DYONISIAN,
  [ASPECT_NAMES.SECRET_HISTORIES]: CONCEPT_TYPES.UNCERTAIN,
  [ASPECT_NAMES.KNOCK]: CONCEPT_TYPES.TRANSCENDANT,
  [ASPECT_NAMES.LANTERN]: CONCEPT_TYPES.APOLLONIAN,
  [ASPECT_NAMES.MOTH]: CONCEPT_TYPES.DYONISIAN,
  [ASPECT_NAMES.MOON]: CONCEPT_TYPES.UNCERTAIN,
  [ASPECT_NAMES.NECTAR]: CONCEPT_TYPES.DYONISIAN,
  [ASPECT_NAMES.ROSE]: CONCEPT_TYPES.APOLLONIAN,
  [ASPECT_NAMES.SCALE]: CONCEPT_TYPES.DYONISIAN,
  [ASPECT_NAMES.SKY]: CONCEPT_TYPES.APOLLONIAN,
  [ASPECT_NAMES.WINTER]: CONCEPT_TYPES.APOLLONIAN,
};

module.exports = {
  CONCEPT_TYPES,
  ASPECT_CONCEPTS,
};
