const { ASPECT_NAMES } = require("./core");

const ASPECT_WEIGHTS = {
  [ASPECT_NAMES.EDGE]: 5,
  [ASPECT_NAMES.FORGE]: 5,
  [ASPECT_NAMES.GRAIL]: 5,
  [ASPECT_NAMES.HEART]: 5,
  [ASPECT_NAMES.SECRET_HISTORIES]: 0,
  [ASPECT_NAMES.KNOCK]: 5,
  [ASPECT_NAMES.LANTERN]: 5,
  [ASPECT_NAMES.MOTH]: 5,
  [ASPECT_NAMES.MOON]: 3,
  [ASPECT_NAMES.NECTAR]: 3,
  [ASPECT_NAMES.ROSE]: 3,
  [ASPECT_NAMES.SCALE]: 3,
  [ASPECT_NAMES.SKY]: 3,
  [ASPECT_NAMES.WINTER]: 5,
};

const CHANCE_OF_STAINS = 0.6;

module.exports = {
  ASPECT_WEIGHTS,
  CHANCE_OF_STAINS,
};
