const { HOUR_NAMES } = require("./names");
const { ASPECT_NAMES, PRECURSOR_ASPECT_NAMES } = require("../aspects/core");

const HOUR_PRIMARY_ASPECTS = {
  [HOUR_NAMES.MOTH]: ASPECT_NAMES.MOTH,
  [HOUR_NAMES.WATCHMAN]: ASPECT_NAMES.LANTERN,
  [HOUR_NAMES.VELVET]: ASPECT_NAMES.HEART,
  [HOUR_NAMES.MALACHITE]: ASPECT_NAMES.NECTAR,
  [HOUR_NAMES.THUNDERSKIN]: ASPECT_NAMES.HEART,
  [HOUR_NAMES.MOTHER_OF_ANTS]: ASPECT_NAMES.KNOCK,
  [HOUR_NAMES.WITCH_AND_SISTER]: ASPECT_NAMES.GRAIL,
  [HOUR_NAMES.COLONEL]: ASPECT_NAMES.EDGE,
  [HOUR_NAMES.LIONSMITH]: ASPECT_NAMES.EDGE,
  [HOUR_NAMES.ELEGIAST]: ASPECT_NAMES.WINTER,
  [HOUR_NAMES.BEACHCOMBER]: ASPECT_NAMES.SKY,
  [HOUR_NAMES.MENISCATE]: ASPECT_NAMES.MOON,
  [HOUR_NAMES.SUN_IN_RAGS]: ASPECT_NAMES.LANTERN,
  [HOUR_NAMES.HORNED_AXE]: ASPECT_NAMES.KNOCK,
  [HOUR_NAMES.MADRUGAD]: ASPECT_NAMES.WINTER,
  [HOUR_NAMES.RED_GRAIL]: ASPECT_NAMES.GRAIL,
  [HOUR_NAMES.WOLF_DIVIDED]: ASPECT_NAMES.EDGE,
  [HOUR_NAMES.VAGABOND]: ASPECT_NAMES.ROSE,
  [HOUR_NAMES.SISTER_AND_WITCH]: ASPECT_NAMES.HEART,
  [HOUR_NAMES.FLOWERMAKER]: ASPECT_NAMES.GRAIL,
  [HOUR_NAMES.FORGE_OF_DAYS]: ASPECT_NAMES.FORGE,
  [HOUR_NAMES.GIRIBRAGO]: ASPECT_NAMES.KNOCK,
  [HOUR_NAMES.CROWNED_GROWTH]: ASPECT_NAMES.WINTER,
  [HOUR_NAMES.MARE]: ASPECT_NAMES.KNOCK,
  [HOUR_NAMES.SEVEN_COILS]: ASPECT_NAMES.EDGE,
  [HOUR_NAMES.WHEEL]: ASPECT_NAMES.MOON,
  [HOUR_NAMES.FLINT]: ASPECT_NAMES.SCALE,
  [HOUR_NAMES.EGG]: ASPECT_NAMES.SCALE,
  [HOUR_NAMES.BLACKBONE]: ASPECT_NAMES.MOON,
  [HOUR_NAMES.APPLEBRIGHT]: ASPECT_NAMES.NECTAR,
  [HOUR_NAMES.TIDE]: ASPECT_NAMES.GRAIL,
  [HOUR_NAMES.SNOW]: ASPECT_NAMES.WINTER,
};

const HOUR_ASPECTS = {
  [HOUR_NAMES.MOTH]: [ASPECT_NAMES.MOTH],
  [HOUR_NAMES.WATCHMAN]: [ASPECT_NAMES.LANTERN],
  [HOUR_NAMES.VELVET]: [
    ASPECT_NAMES.HEART,
    ASPECT_NAMES.MOTH,
    ASPECT_NAMES.MOON,
  ],
  [HOUR_NAMES.MALACHITE]: [
    ASPECT_NAMES.NECTAR,
    ASPECT_NAMES.MOTH,
    ASPECT_NAMES.HEART,
  ],
  [HOUR_NAMES.THUNDERSKIN]: [ASPECT_NAMES.HEART, ASPECT_NAMES.SKY],
  [HOUR_NAMES.MOTHER_OF_ANTS]: [ASPECT_NAMES.KNOCK, ASPECT_NAMES.SECRET_HISTORIES],
  [HOUR_NAMES.WITCH_AND_SISTER]: [
    ASPECT_NAMES.GRAIL,
    ASPECT_NAMES.MOON,
    ASPECT_NAMES.HEART,
  ],
  [HOUR_NAMES.COLONEL]: [
    ASPECT_NAMES.EDGE,
    ASPECT_NAMES.WINTER,
    ASPECT_NAMES.LANTERN,
  ],
  [HOUR_NAMES.LIONSMITH]: [
    ASPECT_NAMES.EDGE,
    ASPECT_NAMES.FORGE,
    ASPECT_NAMES.HEART,
  ],
  [HOUR_NAMES.ELEGIAST]: [
    ASPECT_NAMES.WINTER,
  ],
  [HOUR_NAMES.BEACHCOMBER]: [
    ASPECT_NAMES.SKY,
    ASPECT_NAMES.GRAIL,
    ASPECT_NAMES.KNOCK,
  ],
  [HOUR_NAMES.MENISCATE]: [
    ASPECT_NAMES.MOON,
    ASPECT_NAMES.KNOCK,
    ASPECT_NAMES.LANTERN,
  ],
  [HOUR_NAMES.SUN_IN_RAGS]: [ASPECT_NAMES.LANTERN, ASPECT_NAMES.WINTER],
  [HOUR_NAMES.HORNED_AXE]: [
    ASPECT_NAMES.KNOCK,
    ASPECT_NAMES.SCALE,
    ASPECT_NAMES.WINTER,
  ],
  [HOUR_NAMES.MADRUGAD]: [ASPECT_NAMES.WINTER, ASPECT_NAMES.FORGE],
  [HOUR_NAMES.RED_GRAIL]: [ASPECT_NAMES.GRAIL],
  [HOUR_NAMES.WOLF_DIVIDED]: [
    ASPECT_NAMES.EDGE,
    ASPECT_NAMES.WINTER,
    ASPECT_NAMES.SCALE,
  ],
  [HOUR_NAMES.VAGABOND]: [
    ASPECT_NAMES.ROSE,
    ASPECT_NAMES.MOTH,
    ASPECT_NAMES.SECRET_HISTORIES,
  ],
  [HOUR_NAMES.SISTER_AND_WITCH]: [
    ASPECT_NAMES.HEART,
    ASPECT_NAMES.MOTH,
    ASPECT_NAMES.GRAIL,
  ],
  [HOUR_NAMES.FLOWERMAKER]: [ASPECT_NAMES.GRAIL, ASPECT_NAMES.LANTERN],
  [HOUR_NAMES.FORGE_OF_DAYS]: [ASPECT_NAMES.FORGE],
  [HOUR_NAMES.GIRIBRAGO]: [
    ASPECT_NAMES.KNOCK,
    ASPECT_NAMES.MOTH,
    ASPECT_NAMES.SKY,
  ],
  [HOUR_NAMES.CROWNED_GROWTH]: [ASPECT_NAMES.WINTER, ASPECT_NAMES.HEART],
  [HOUR_NAMES.MARE]: [ASPECT_NAMES.KNOCK, ASPECT_NAMES.MOTH, ASPECT_NAMES.NECTAR],
  [HOUR_NAMES.SEVEN_COILS]: [
    ASPECT_NAMES.EDGE,
    ASPECT_NAMES.KNOCK,
    ASPECT_NAMES.SECRET_HISTORIES,
  ],
  [HOUR_NAMES.WHEEL]: [
    ASPECT_NAMES.MOON,
    ASPECT_NAMES.NECTAR,
    ASPECT_NAMES.HEART,
  ],
  [HOUR_NAMES.FLINT]: [ASPECT_NAMES.SCALE, ASPECT_NAMES.FORGE],
  [HOUR_NAMES.EGG]: [ASPECT_NAMES.SCALE, ASPECT_NAMES.LANTERN],
  [HOUR_NAMES.BLACKBONE]: [ASPECT_NAMES.MOON, ASPECT_NAMES.SCALE],
  [HOUR_NAMES.APPLEBRIGHT]: [ASPECT_NAMES.NECTAR, ASPECT_NAMES.GRAIL],
  [HOUR_NAMES.TIDE]: [ASPECT_NAMES.GRAIL, ASPECT_NAMES.SCALE],
  [HOUR_NAMES.SNOW]: [ASPECT_NAMES.WINTER],
};

// Hours requiring at least two Aspect Matches to be viable results
const HOURS_REQUIRING_AT_LEAST_TWO = [
  HOUR_NAMES.CROWNED_GROWTH,
  HOUR_NAMES.MARE,
  HOUR_NAMES.SEVEN_COILS,
  HOUR_NAMES.WHEEL,
  HOUR_NAMES.GIRIBRAGO,
  HOUR_NAMES.FLINT,
  HOUR_NAMES.EGG,
  HOUR_NAMES.BLACKBONE,
  HOUR_NAMES.APPLEBRIGHT,
  HOUR_NAMES.TIDE,
];

const HOUR_PRECURSOR_ASPECTS = {
  [HOUR_NAMES.WHEEL]: PRECURSOR_ASPECT_NAMES.WHEEL,
  [HOUR_NAMES.EGG]: PRECURSOR_ASPECT_NAMES.EGG,
  [HOUR_NAMES.FLINT]: PRECURSOR_ASPECT_NAMES.FLINT,
  [HOUR_NAMES.SEVEN_COILS]: PRECURSOR_ASPECT_NAMES.FANG,
  [HOUR_NAMES.TIDE]: PRECURSOR_ASPECT_NAMES.TIDE,
};

// eslint-disable-next-line no-unused-vars
const _unfilledHours = {
  [HOUR_NAMES.RISING_SPIDER]: [],
  [HOUR_NAMES.WITNESS]: [],
  [HOUR_NAMES.CHANDLER]: [],
  [HOUR_NAMES.SUN_IN_SPLENDOUR]: [],
  [HOUR_NAMES.NEW_KING]: [],
};

module.exports = {
  HOUR_PRIMARY_ASPECTS,
  HOUR_ASPECTS,
  HOURS_REQUIRING_AT_LEAST_TWO,
  HOUR_PRECURSOR_ASPECTS,
};
