const { HOUR_NAMES } = require("./names");

const HOUR_DESCRIPTIONS = {
  [HOUR_NAMES.MOTH]: `The ${HOUR_NAMES.MOTH} is an Hour originally worshipped by the ancestors of humanity, who took part in overthrowing the Gods-from-Stone by hunting and stealing the skin of The ${HOUR_NAMES.WHEEL}.\nMoth, the aspect of chaos and yearning, is named after him. He yearns for the Glory, quite literally being a moth seeking out light. Moth's followers tend to be barbers, stealthy types and shapechangers. Or lunatics.`,
  [HOUR_NAMES.WATCHMAN]: `'We call upon the Watchman, who navigates; who illuminates; who is not compassionate.'\nA merciless Hour of knowledge and Enlightement, and a favorite amongst those who have ambitions of immortality through Lantern.`,
  [HOUR_NAMES.VELVET]: `The ${HOUR_NAMES.VELVET} woke when the wood-roots tasted blood. A burrowing secret-keeper, providing shelter and concealment to those she favors.\nUnlike The ${HOUR_NAMES.MOTH} she prefers to stay in the darkness of the Wood, hiding the secrets she collects from the world.`,
  [HOUR_NAMES.MALACHITE]: `The ${HOUR_NAMES.MALACHITE}; The Ring-Yew is an 'old and fecund' hour of the Wood, whose domains include desire, restlessness and whimsy.\nShe is known to have a forbidden relationship with one of the Gods-from-Nowhere - and such things are truly forbidden.\n\nHer unique servants are a type of risen corpse renewed by her honey, and sustained by the growths of the Wood.`,
  [HOUR_NAMES.THUNDERSKIN]: `The ${HOUR_NAMES.THUNDERSKIN}, often portrayed as an anatomical heart, was once a mortal musician who loved The ${HOUR_NAMES.RED_GRAIL}, ascended by being 'reborn from blood' and now beats endlessly as a being of storms, dance, and eternity.\nThe ${HOUR_NAMES.THUNDERSKIN} acts as a Protector of the world, and it's creations and followers will. Not. Stop. Dancing.`,
  [HOUR_NAMES.MOTHER_OF_ANTS]: `The ${HOUR_NAMES.MOTHER_OF_ANTS}, who encircles; who opens; who arises from wounds.\nA former mortal priestess who ascended after assisting the ${HOUR_NAMES.COLONEL} in slaying the ${HOUR_NAMES.SEVEN_COILS}. She arose from the blood of the dead god-from-stone, and now opens the way for others.`,
  [HOUR_NAMES.WITCH_AND_SISTER]: `The Twins are the pair of Hours -  the Sister-and-Witch and the Witch-and-Sister - who formed from the union of two mortals. Born in two wombs, one was a princess, the other a monster. In loving union they drowned.\nThe Witch-and-Sister is the hungrier of the two faces.`,
  [HOUR_NAMES.COLONEL]: `The ${HOUR_NAMES.COLONEL}, who is blind, who is scarred; who cannot be denied. His scars make him impossible to wound. He had himself blinded and scarred, so that the ${HOUR_NAMES.SEVEN_COILS} could not harm him further; slaying the Serpent after.\n\nIn violence and rivalry, the ${HOUR_NAMES.COLONEL} prefers patience and cunning, and he favors those who promote the political status quo and betray revolutions.`,
  [HOUR_NAMES.LIONSMITH]: `The nature of the ${HOUR_NAMES.LIONSMITH} is to be stronger; to be seamless; to make monsters. The Lionsmith once shattered his sword with his bare hands; betraying and starting a legendary rivalry with the ${HOUR_NAMES.COLONEL}.\n\nThe ${HOUR_NAMES.LIONSMITH} is a furious Hour of strength, rebellion, and growing ever stronger.`,
  [HOUR_NAMES.ELEGIAST]: `The world forgets; but the Ivory Dove does not. The ${HOUR_NAMES.ELEGIAST} commemorates and grieves, and is heavily associated with memory, loss and death. While not the kindest of the Hours, he is never cruel - and remembers all his promises.\n\nHe is the power which prevents the world from forgetting the lost.`,
  [HOUR_NAMES.BEACHCOMBER]: `The ${HOUR_NAMES.BEACHCOMBER} is a thief, a spy, and a voyeur, though he claims his treasures are found, not stolen. He has been known to share some of his collected knowledge with others at times, and to help others in the discovery of hidden things - though he is known to keep his most treasured secrets to himself.`,
  [HOUR_NAMES.MENISCATE]: `The ${HOUR_NAMES.MENISCATE} is one of the Solar Hours, created from the division of the sun. Her face is a wounded mirror, and she presides of the House of the Moon - a secret reflection of the world, as is.\nShe favours balance, and her followers claim her beauty is truly unmatched.`,
  [HOUR_NAMES.SUN_IN_RAGS]: `The ${HOUR_NAMES.SUN_IN_RAGS}; distant, not as it was; which burns still. The hour of beautiful endings. It's appearance is a grim reminder of the True Sun's former glory and sorrowful end.\nWhen the Sun was divided, the ${HOUR_NAMES.SUN_IN_RAGS} turned cold - a shattered, departing sunset.`,
  [HOUR_NAMES.HORNED_AXE]: `The ${HOUR_NAMES.HORNED_AXE} is the last of the gods-from-stone - Hours who existed before humanity. She remains as a liminal guardian of the Threshold. She separates and distinguishes, watching over the boundaries of the Mansus.\nShe is enemies with The Twins, as their nature is to unify, while hers is to divide.`,
  [HOUR_NAMES.MADRUGAD]: `The ${HOUR_NAMES.MADRUGAD} is one of the Solar Hours; a fragment of the the shattered True Sun. Even before that, she recognized as an aspect of the chilly winter dawn, who presided over death and the passage of the Dead.\nThe ${HOUR_NAMES.MADRUGAD} oversees the Cindered Tally, from which years and decades are stolen by mortals to prolong their own life and youth.`,
  [HOUR_NAMES.RED_GRAIL]: `The ${HOUR_NAMES.RED_GRAIL} is the Hour which the aspect of birth, desire and blood is named after. Her followers of the Red Church endlessly labour to birth new sensations and desires.\nOnce these were the domains of the ${HOUR_NAMES.TIDE}; an endless ocean. Unfortunately for them, the ${HOUR_NAMES.RED_GRAIL} has an endless thirst.`,
  [HOUR_NAMES.WOLF_DIVIDED]: `The ${HOUR_NAMES.WOLF_DIVIDED} is the youngest Hour, born as a wound of The Sun. The wolf's nature is violently nihilistic, possessing both an insatiable appetite for destruction and desire for all of reality to end, so that he may finally consume himself and end his own painful existence.`,
  [HOUR_NAMES.VAGABOND]: `The ${HOUR_NAMES.VAGABOND}, who tells her tale to the willing and the unwilling. Who goes by many, many names. A rogue Hour who cannot enter the Mansus - but wanders everywhere else. She claims to be the only one with knowledge of all of history.`,
  [HOUR_NAMES.SISTER_AND_WITCH]: `The Twins are the pair of Hours -  the Sister-and-Witch and the Witch-and-Sister - who formed from the union of two mortals. Born in two wombs, one was a princess, the other a monster. In loving union they drowned.\nThe Sister-and-Witch is stronger in heart; a healer, ensuring survival.`,
  [HOUR_NAMES.FLOWERMAKER]: `The ${HOUR_NAMES.FLOWERMAKER} cannot harm you; he cannot find you; and he always has what you desire. A 'greedy power of things TOO wonderful to bear', the ${HOUR_NAMES.FLOWERMAKER} promises to fulfill one's desires, if they are only able to find him. His themes of flowers, dreams and intoxicating pleasures are likely a connection to Opium Dens of old.`,
  [HOUR_NAMES.FORGE_OF_DAYS]: `The ${HOUR_NAMES.FORGE_OF_DAYS} is the Hour of destructive change, from which the aspect of Forge takes its name. She is perhaps best known for dividing the True Sun, whom she loved.\nHer nature is to constantly remake and change. To ignite sparks of rebellion, and to thrive in industrial progress.`,
  [HOUR_NAMES.GIRIBRAGO]: `He contains; He brings gifts; he does not destroy.\nThe ${HOUR_NAMES.GIRIBRAGO} is an obscure Hour of which little is known, who might be cast down into Nowhere.. Or to some decree, has replaced parts of the Sun.\n\nThe ${HOUR_NAMES.GIRIBRAGO} is said to have "burst forth from the mountains", being Stone, Diamond, and emanating a powerful aura of life.`,
  [HOUR_NAMES.CROWNED_GROWTH]: `The ${HOUR_NAMES.CROWNED_GROWTH} is a perilous Hour from Nowhere, who seeks to "infect and become". His is the power of lust and disease, his the will to infect and become. Do not permit him to touch you. It hungers to transform all of reality into itself. Even looking upon it is hinted to be dangerous.`,
  [HOUR_NAMES.MARE]: `The ${HOUR_NAMES.MARE}. She is a god-from-Nowhere, who despite being presented as friendly is one of hte most perilous Hours. The Mare has a forbidden relationship with the ${HOUR_NAMES.MALACHITE} - and forbidden things have power.\nShe longs to steal you away. She yearns to corrupt, contaminate, seduce and gossip. Most concerningly, she is unknowable.`,
  [HOUR_NAMES.SEVEN_COILS]: `The ${HOUR_NAMES.SEVEN_COILS} was one of the gods-from-stone, predating humanity. It was slain by the ${HOUR_NAMES.COLONEL} with help of the ${HOUR_NAMES.MOTHER_OF_ANTS}.\n\nIt is described as a flabby, fanged creature of monstrous size, the colour of sand and sulphur, with multiple tentacle-necks tearing at its own flesh.\nIts blood that flows is golden, opening the way for humanity to ascend.`,
  [HOUR_NAMES.WHEEL]: `The ${HOUR_NAMES.WHEEL} was one of the Hours before mankind - a precursor of Heart and Moth before the ${HOUR_NAMES.MOTH} usurped it from within and stole its skin.\nDespite its death, the ${HOUR_NAMES.WHEEL} still turns in the House of the Moon. It once acted as some sort of protector of the world, and it is believed that with each turn, pulse and wriggle - it will one day return.`,
  [HOUR_NAMES.FLINT]: `The ${HOUR_NAMES.FLINT} was one of the old gods-from-stone worshipped before humanity. An old fire usurped and extuingished by the Forge; a dead god of fire and creation.\nShe is described as a smooth stone sharpened to a midnight point, whose facets glint with light.\nIt seems to have filled a similar role to the ${HOUR_NAMES.FORGE_OF_DAYS}; which shattered and eclipsed her.\n\nShe invented the arts of shaping and remaking, and carries the proto-connection to fire.`,
  [HOUR_NAMES.EGG]: `"The Sun was warmer once - no brighter, but its touch was a kind of mercy".\nThe ${HOUR_NAMES.EGG} was one of the gods-rom stone, who ruled before humanity. It once was the pale-white gold sun, peeking out through the mists. It is said that he offered protection to humanity in exchange for blood sacrifices, until one day a foolish mortal stole some of its light.`,
  [HOUR_NAMES.APPLEBRIGHT]: `The ${HOUR_NAMES.APPLEBRIGHT} is a mysterious Hour from Nowhere, thought to be the counterpart of the ${HOUR_NAMES.FLOWERMAKER}. Her followers specialize in horticulture and medicine. Despite her association with healing, the ${HOUR_NAMES.APPLEBRIGHT} is described as having the power to cause harm if "invited" to do so.\n\nThe poisoned apple iconography suggests this harm would be brought on by one's own actions. After all, like The ${HOUR_NAMES.FLOWERMAKER}, she is linked to the 'unwise' nature of desires. The eternal sheen of youth could mask a deepening rot.`,
  [HOUR_NAMES.BLACKBONE]: `The ${HOUR_NAMES.BLACKBONE} is one of the Hours about which little information is currently known. Its most understood aspect is her connection Grail and the Sea; supposedly, she is 'sated' by the sinking of ships.\n\nSome speculate the ${HOUR_NAMES.BLACKBONE} is what remained when the Grail drank the Tide. Others attribute the existance of earthquakes to "Her limbs being further fractured".`,
};

const HOUR_DOMAINS = {
  [HOUR_NAMES.MOTH]: `Chaos, yearning, passion, shedding the self (hair or skin or identity)`,
  [HOUR_NAMES.WATCHMAN]: `Light (and to an extent shadow), reason, enlightenment, mercilessness`,
  [HOUR_NAMES.VELVET]: `Secrecy, darkness (and the protection both afford against the merciless of light)`,
  [HOUR_NAMES.MALACHITE]: `Fertility, whimsy, renewal, plant life, bees`,
  [HOUR_NAMES.THUNDERSKIN]: ` Song, dance, vitality, storms, flaying, ceaselessness`,
  [HOUR_NAMES.MOTHER_OF_ANTS]: `Wounds as openings, locks and locksmiths, serpents, poisons, martyrship`,
  [HOUR_NAMES.WITCH_AND_SISTER]: `Merged identity, partnerships, desire in a relationship, liminal spaces (crossroads, coastlines), the sea (esp drowning), the moon`,
  [HOUR_NAMES.COLONEL]: `Cunning, methodical warfare, old age, the status quo, loyalty, patience, scars, humanity`,
  [HOUR_NAMES.LIONSMITH]: `Strength, heroic warfare, youth, rebellion, betrayal, bravery, vigor, monster-making`,
  [HOUR_NAMES.ELEGIAST]: `Remembrance, grief, the dead`,
  [HOUR_NAMES.BEACHCOMBER]: `Greed, spies, voyeurs, yearning, gossip`,
  [HOUR_NAMES.MENISCATE]: `The moon, mirrors, reflections (mundane and inverted spaces), revelation, beauty, clarity, night`,
  [HOUR_NAMES.SUN_IN_RAGS]: `Beautiful endings, sunset`,
  [HOUR_NAMES.HORNED_AXE]: `Thresholds`,
  [HOUR_NAMES.MADRUGAD]: `Stillness, precision, forgetting, death and passage into 'the Mansus'`,
  [HOUR_NAMES.RED_GRAIL]: `Hunger, thirst, lust, sex, desire, birth, blood`,
  [HOUR_NAMES.WOLF_DIVIDED]: `Agony, horrible warfare, wounds, hatred`,
  [HOUR_NAMES.VAGABOND]: `Exploration, wanderlust`,
  [HOUR_NAMES.SISTER_AND_WITCH]: `Merged identity, partnerships, comfort in a relationship, liminal spaces (crossroads, coastlines), the sea (esp drowning), the moon`,
  [HOUR_NAMES.FLOWERMAKER]: `Fantasy, dreams, addictive & self-destructing pleasures, greed`,
  [HOUR_NAMES.FORGE_OF_DAYS]: `Fire, creation, destruction, transformation, ingenuity`,
  [HOUR_NAMES.GIRIBRAGO]: `Mountains, volcanoes, preservation, gifts, light, whimsy`,
  [HOUR_NAMES.CROWNED_GROWTH]: `Lust, disease, infection, assimilation, fungi`,
  [HOUR_NAMES.MARE]: `Deception, false friends, gossip, trickery, destruction of knowledge`,
  [HOUR_NAMES.SEVEN_COILS]: `Monsters, wounds, the convolutions of time`,
  [HOUR_NAMES.WHEEL]: `Eternity, thunder, the Wood, primitive life`,
  [HOUR_NAMES.FLINT]: `Primitive tools, fire, the earth and its treasures, the stars`,
  [HOUR_NAMES.EGG]: `Mercy, the sun, the moon, flight, serpents`,
  [HOUR_NAMES.APPLEBRIGHT]: `Youth, healing, mutation`,
  [HOUR_NAMES.BLACKBONE]: `The crushing black depths of the deep sea`,
};

const HOUR_SINGLETON_DOMAINS = {
  [HOUR_NAMES.HORNED_AXE]: true,
  [HOUR_NAMES.BLACKBONE]: true,
}

module.exports = {
  HOUR_DESCRIPTIONS,
  HOUR_DOMAINS,
  HOUR_SINGLETON_DOMAINS
};
