const { HOUR_NAMES } = require("./names");

const HOUR_IMAGES = {
    [HOUR_NAMES.MOTH]: 'moth.jpg',
    [HOUR_NAMES.WATCHMAN]: 'watchman.jpg',
    [HOUR_NAMES.VELVET]: 'velvet.jpg',
    [HOUR_NAMES.MALACHITE]: 'malachite.jpg',
    [HOUR_NAMES.THUNDERSKIN]: 'thunderskin.jpg',
    [HOUR_NAMES.MOTHER_OF_ANTS]: 'mother-of-ants.jpg',
    [HOUR_NAMES.WITCH_AND_SISTER]: 'witch-sister.jpg',
    [HOUR_NAMES.COLONEL]: 'colonel.jpg',
    [HOUR_NAMES.LIONSMITH]: 'lionsmith.jpg',
    [HOUR_NAMES.ELEGIAST]: 'elegiast.jpg',
    [HOUR_NAMES.BEACHCOMBER]: 'beachcomber.jpg',
    [HOUR_NAMES.MENISCATE]: 'meniscate.jpg',
    [HOUR_NAMES.SUN_IN_RAGS]: 'sun-in-rags.jpg',
    [HOUR_NAMES.HORNED_AXE]: 'horned-axe.jpg',
    [HOUR_NAMES.MADRUGAD]: 'madrugad.jpg',
    [HOUR_NAMES.RED_GRAIL]: 'red-grail.jpg',
    [HOUR_NAMES.WOLF_DIVIDED]: 'wolf-divided.jpg',
    [HOUR_NAMES.VAGABOND]: 'vagabond.jpg',
    [HOUR_NAMES.SISTER_AND_WITCH]: 'sister-witch.jpg',
    [HOUR_NAMES.FLOWERMAKER]: 'flowermaker.jpg',
    [HOUR_NAMES.FORGE_OF_DAYS]: 'forge-of-days.jpg',
    [HOUR_NAMES.GIRIBRAGO]: 'the-giribrago-by-heyu-6466.png',
    // [HOUR_NAMES.SNOW]: ',
    [HOUR_NAMES.BLACKBONE]: 'the-blackbone-by-heyu-6466.png',
    // [HOUR_NAMES.RISING_SPIDER]: ',
    [HOUR_NAMES.CROWNED_GROWTH]: 'crowned-growth.jpg',
    [HOUR_NAMES.APPLEBRIGHT]: 'the-applebright-by-heyu-6466.png',
    [HOUR_NAMES.MARE]: 'mare.jpg',
    // [HOUR_NAMES.WITNESS]: '',
    [HOUR_NAMES.CHANDLER]: 'the-chandler-by-heyu-6466.png',
    [HOUR_NAMES.SEVEN_COILS]: 'seven-coils-by-roashe.jpg',
    [HOUR_NAMES.WHEEL]: 'the-wheel-by-roashe.jpg',
    [HOUR_NAMES.FLINT]: 'flint-by-roashe.png',
    [HOUR_NAMES.EGG]: 'egg-unhatching-by-roashe.jpg',
    [HOUR_NAMES.TIDE]: 'the-tide-by-roashe.png',
    [HOUR_NAMES.NEW_KING]: 'new-king-by-heyu-6466.jpg',
    // [HOUR_NAMES.SUN_IN_SPLENDOUR]: ',
};

const HOUR_ART_IS_UNOFFICIAL = {
    [HOUR_NAMES.GIRIBRAGO]: true,
    [HOUR_NAMES.BLACKBONE]: true,
    [HOUR_NAMES.APPLEBRIGHT]: true,
    [HOUR_NAMES.CHANDLER]: true,
    [HOUR_NAMES.CHANDLER]: true,
    [HOUR_NAMES.WHEEL]: true,
    [HOUR_NAMES.SEVEN_COILS]: true,
    [HOUR_NAMES.TIDE]: true,
    [HOUR_NAMES.EGG]: true,
    [HOUR_NAMES.FLINT]: true,
    [HOUR_NAMES.NEW_KING]: true,
};

module.exports = {
    HOUR_IMAGES,
    HOUR_ART_IS_UNOFFICIAL,
}