const { HOUR_NAMES } = require("./names");

const HOUR_NUMBERS = {
  [HOUR_NAMES.MOTH]: 0,
  [HOUR_NAMES.WATCHMAN]: 1,
  [HOUR_NAMES.VELVET]: 2,
  [HOUR_NAMES.MALACHITE]: 3,
  [HOUR_NAMES.THUNDERSKIN]: 4,
  [HOUR_NAMES.MOTHER_OF_ANTS]: 5,
  [HOUR_NAMES.WITCH_AND_SISTER]: 6,
  [HOUR_NAMES.COLONEL]: 7,
  [HOUR_NAMES.LIONSMITH]: 8,
  [HOUR_NAMES.ELEGIAST]: 9,
  [HOUR_NAMES.BEACHCOMBER]: 10,
  [HOUR_NAMES.MENISCATE]: 11,
  [HOUR_NAMES.SUN_IN_RAGS]: 12,
  [HOUR_NAMES.HORNED_AXE]: 13,
  [HOUR_NAMES.MADRUGAD]: 14,
  [HOUR_NAMES.RED_GRAIL]: 15,
  [HOUR_NAMES.WOLF_DIVIDED]: 16,
  [HOUR_NAMES.VAGABOND]: 17,
  [HOUR_NAMES.SISTER_AND_WITCH]: 18,
  [HOUR_NAMES.FLOWERMAKER]: 19,
  [HOUR_NAMES.FORGE_OF_DAYS]: 20,

  [HOUR_NAMES.GIRIBRAGO]: 21,
  [HOUR_NAMES.SNOW]: 22,
  [HOUR_NAMES.BLACKBONE]: 23,

  [HOUR_NAMES.RISING_SPIDER]: 24,
  [HOUR_NAMES.CROWNED_GROWTH]: 25,
  [HOUR_NAMES.APPLEBRIGHT]: 26,
  [HOUR_NAMES.MARE]: 27,
  [HOUR_NAMES.WITNESS]: 28,

  [HOUR_NAMES.CHANDLER]: 29,

  [HOUR_NAMES.SEVEN_COILS]: null,
  [HOUR_NAMES.WHEEL]: null,
  [HOUR_NAMES.FLINT]: null,
  [HOUR_NAMES.EGG]: null,
  [HOUR_NAMES.TIDE]: null,
  [HOUR_NAMES.SUN_IN_SPLENDOUR]: null,
};

const HOUR_WEIGHTS = {
  TAROT: 8,
  NON_TAROT: 2,
};

module.exports = {
  HOUR_NUMBERS,
  HOUR_WEIGHTS,
};
